#### Fauzan Taufik
#### ML Developer Engeener


- Numpy concatanation
- Pandas concat
    - Axis
    - Catching error for sama index
    - Ignore index
    - concat with join
- Pandas Append
- merge/join
    - one to one
    - many to one
    - many to many
    - Merge with specified key
    - Aritmatik Join

In [ ]:
- Concat
- Append
- Merge

In [2]:
import numpy as np
import pandas as pd

In [5]:
x = [1, 2, 3, 4]
y = [5, 6, 7, 8]
z = [9, 10, 1, 2]

In [6]:
gabung_array = [x, y, z]
np.concatenate(gabung_array)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  1,  2])

In [8]:
x = [[1, 2],
     [3, 4]]

In [ ]:
[[1, 2],
[3, 4],
[1, 2],
 [3, 4]]

In [ ]:
[[1, 2, 1, 2],
[3, 4, 3, 4],
]

In [14]:
b = np.array([[1, 2, 1, 2],
[3, 4, 3, 4],
])

In [15]:
b.shape

(2, 4)

In [12]:
np.concatenate([x, x], axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [16]:
np.concatenate([x, x], axis=0)

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [20]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['A', 'B', 'F'], index=[1, 2, 6])

In [22]:
pd.concat([ser1, ser2], axis=0)

1    A
2    B
3    C
1    A
2    B
6    F
dtype: object

In [43]:
def make_df(cols, index):
    data = {c : [str(c) + str(i) for i in index] for c in cols}
    return pd.DataFrame(data)

In [27]:
df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [4, 5])

In [28]:
df1

A  B
0  1  1
1  2  2

In [29]:
df2

A  B
0  4  4
1  5  5

In [33]:
pd.concat([df1, df2], axis=1, keys=['df1', 'df2'])

df1    df2   
    A  B   A  B
0   1  1   4  4
1   2  2   5  5

In [32]:
pd.concat?

In [36]:
pd.concat([df1, df2], axis=0)

A  B
0  1  1
1  2  2
0  4  4
1  5  5

In [34]:
df1

A  B
0  1  1
1  2  2

In [35]:
df2

A  B
0  4  4
1  5  5

In [38]:
pd.concat?

In [40]:
pd.concat([df1, df2], axis=0, ignore_index=True)

A  B
0  1  1
1  2  2
2  4  4
3  5  5

In [42]:
pd.concat([df1, df2], join='inner')

A  B
0  1  1
1  2  2
0  4  4
1  5  5

In [45]:
make_df('ABC' ,range(4))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3

In [47]:
df1 = make_df('ABC', range(2))
df2 = make_df('BCD', range(2))

In [48]:
df1

A   B   C
0  A0  B0  C0
1  A1  B1  C1

In [49]:
df2

B   C   D
0  B0  C0  D0
1  B1  C1  D1

In [54]:
df2[df2['D']=='D1']

B   C   D
1  B1  C1  D1

In [55]:
pd.concat([df1, df2[df2['D']=='D1']], join='inner')

B   C
0  B0  C0
1  B1  C1
1  B1  C1

In [57]:
df1

A   B   C
0  A0  B0  C0
1  A1  B1  C1

In [58]:
df2

B   C   D
0  B0  C0  D0
1  B1  C1  D1

In [59]:
df1.append(df2)

A   B   C    D
0   A0  B0  C0  NaN
1   A1  B1  C1  NaN
0  NaN  B0  C0   D0
1  NaN  B1  C1   D1

In [60]:
df1.append?

In [61]:
obj_list = [1, 2]

In [62]:
obj_list.append(3)

In [63]:
obj_list

[1, 2, 3]

In [64]:
df1.append(df2)

A   B   C    D
0   A0  B0  C0  NaN
1   A1  B1  C1  NaN
0  NaN  B0  C0   D0
1  NaN  B1  C1   D1

In [65]:
df1

A   B   C
0  A0  B0  C0
1  A1  B1  C1

In [ ]:
- One to One
- Many to One
- Many to Many

In [103]:
df1 = pd.DataFrame(
    {'employee' : ['A', 'D'],
    'role' : ['Engeener', 'Engeener']}
)

df2 = pd.DataFrame({
    'employee' : ['A', 'B', 'C', 'D'],
    'year' : [2013, 2014, 2015, 2018]
})

In [69]:
df1

employee        role
0        A    Engeener
1        B          HR
2        C  Accounting

In [70]:
df2

employee  year
0        A  2013
1        B  2014
2        C  2015

In [71]:
pd.merge(df1, df2)

employee        role  year
0        A    Engeener  2013
1        B          HR  2014
2        C  Accounting  2015

In [80]:
df3 = pd.merge(df1, df2)

In [83]:
df3

employee        role  year
0        A    Engeener  2013
1        B          HR  2014
2        C  Accounting  2015
3        D    Engeener  2018

In [81]:
df4 = pd.DataFrame({
    'role' : ['Engeener', 'HR', 'Accounting'],
    'supervisor' : ['Z', 'X', 'V']
})

In [78]:
df4

role supervisor
0    Engeener          Z
1          HR          X
2  Accounting          V

In [82]:
pd.merge(df3, df4)

employee        role  year supervisor
0        A    Engeener  2013          Z
1        D    Engeener  2018          Z
2        B          HR  2014          X
3        C  Accounting  2015          V

In [ ]:
1. A         1. B
1. D         1. C

In [ ]:
AB
AC
DB
DC

In [96]:
df5 = pd.DataFrame({
    'role' : ['Accounting', 'Account', 'Engeener', 'Engeener', 'HR', 'HR', 'Developer'],
    'skill' : ['math', 'spredsheet', 'coding', 'linux', 'spreadsheet', 'management', 'Python']
})

In [97]:
df5

role        skill
0  Accounting         math
1     Account   spredsheet
2    Engeener       coding
3    Engeener        linux
4          HR  spreadsheet
5          HR   management
6   Developer       Python

In [98]:
df1

employee       group
0        A    Engeener
1        B          HR
2        C  Accounting
3        D    Engeener

In [ ]:
A Coding
A linux
D Coding
D Linux

In [88]:
pd.merge(df1, df5)

employee        role        skill
0        A    Engeener       coding
1        A    Engeener        linux
2        D    Engeener       coding
3        D    Engeener        linux
4        B          HR  spreadsheet
5        B          HR   management
6        C  Accounting         math

In [91]:
df1.columns = ['employee', 'group']

In [105]:
df5

role        skill
0  Accounting         math
1     Account   spredsheet
2    Engeener       coding
3    Engeener        linux
4          HR  spreadsheet
5          HR   management
6   Developer       Python

In [107]:
df1.columns = ['employee', 'group']

In [108]:
df1

employee     group
0        A  Engeener
1        D  Engeener

In [110]:
pd.merge(df1, df5, left_on='group', right_on='role', how='right')

employee     group        role        skill
0        A  Engeener    Engeener       coding
1        D  Engeener    Engeener       coding
2        A  Engeener    Engeener        linux
3        D  Engeener    Engeener        linux
4      NaN       NaN  Accounting         math
5      NaN       NaN     Account   spredsheet
6      NaN       NaN          HR  spreadsheet
7      NaN       NaN          HR   management
8      NaN       NaN   Developer       Python

In [95]:
pd.merge?

In [ ]:
- outer
- inner
- left join
- right join