### Numpy

1. Numpy Attributes
    - DImension
    - shape
    - size
    - type
    - Itemsize
    - nbytes
2. Indexing of arrays
    - 
3. Slicing Array
    - [start:stop:step]
    - Multidimension
4. Reshaping Array
    - reshape
5. Joining array
    - concatenate
    
    
### Pandas
1. Pandas Series
    - The difference series with numpy
    - Series and dictionary
2. Pandas DataFrame
    - Pandas and numpy
    - DataFrame and Dictionary

In [105]:
import pandas as pd

obj_series = pd.Series({'Jakarta':20, 'Garut':7,'Bandung':10, 'Jawa':8})
obj_series_area = pd.Series({'Jakarta':30, 'Garut':30,'Bandung':20, 'Jawa':40})

In [122]:
df = pd.DataFrame({
    'Populasi' : [20, 7, 10, 8],
    'Area' : [30, 30, 20, 40]
        }, 
    index = ['Jakarta', 'Garut', 'Bandung', 'Jakarta']
)

In [113]:
pd.DataFrame?

In [125]:
df['Populasi']['Garut']

7

In [126]:
import pandas as pd

In [127]:
!dir

 Volume in drive C has no label.
 Volume Serial Number is 4806-0654

 Directory of C:\Users\LENOVO\Python Data Science\sanbercode 092020

10/05/2020  09:48 PM    <DIR>          .
10/05/2020  09:48 PM    <DIR>          ..
10/05/2020  06:26 PM    <DIR>          .ipynb_checkpoints
09/30/2020  09:04 PM            11,281 Logic Control flow and Loop.ipynb
10/05/2020  09:48 PM            15,044 Numpy Pandas.ipynb
05/08/2020  09:32 PM            24,045 pima indians dataset.csv
10/01/2020  09:22 PM            23,086 Python List dan Dictionary.ipynb
10/03/2020  01:54 PM           117,956 Statistik.ipynb
09/28/2020  09:16 PM             3,983 Tugas Hari 1 (1).ipynb
09/29/2020  09:31 PM             5,466 Tugas Hari 2.ipynb
10/01/2020  09:54 PM            11,269 Tugas Hari 3.ipynb
10/01/2020  07:39 PM            13,653 Tugas Hari 4.ipynb
10/05/2020  08:46 PM            29,634 Tugas Hari 5.ipynb
09/29/2020  09:17 PM             3,229 Untitled.ipynb
              11 File(s)        258,646 bytes
     

In [133]:
df = pd.read_csv('pima indians dataset.csv', names=['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'])

In [138]:
df.tail(10)

A    B   C   D    E     F      G   H  I
758   1  106  76   0    0  37.5  0.197  26  0
759   6  190  92   0    0  35.5  0.278  66  1
760   2   88  58  26   16  28.4  0.766  22  0
761   9  170  74  31    0  44.0  0.403  43  1
762   9   89  62   0    0  22.5  0.142  33  0
763  10  101  76  48  180  32.9  0.171  63  0
764   2  122  70  27    0  36.8  0.340  27  0
765   5  121  72  23  112  26.2  0.245  30  0
766   1  126  60   0    0  30.1  0.349  47  1
767   1   93  70  31    0  30.4  0.315  23  0

In [140]:
df.shape

(768, 9)

In [139]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       768 non-null    int64  
 1   B       768 non-null    int64  
 2   C       768 non-null    int64  
 3   D       768 non-null    int64  
 4   E       768 non-null    int64  
 5   F       768 non-null    float64
 6   G       768 non-null    float64
 7   H       768 non-null    int64  
 8   I       768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [145]:
df.fillna?

In [147]:
df.describe()

A           B           C           D           E           F  \
count  768.000000  768.000000  768.000000  768.000000  768.000000  768.000000   
mean     3.845052  120.894531   69.105469   20.536458   79.799479   31.992578   
std      3.369578   31.972618   19.355807   15.952218  115.244002    7.884160   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      1.000000   99.000000   62.000000    0.000000    0.000000   27.300000   
50%      3.000000  117.000000   72.000000   23.000000   30.500000   32.000000   
75%      6.000000  140.250000   80.000000   32.000000  127.250000   36.600000   
max     17.000000  199.000000  122.000000   99.000000  846.000000   67.100000   

                G           H           I  
count  768.000000  768.000000  768.000000  
mean     0.471876   33.240885    0.348958  
std      0.331329   11.760232    0.476951  
min      0.078000   21.000000    0.000000  
25%      0.243750   24.000000    0.000000  
50%      0.372500   29.000000    0.000000  
75%      0.626250   41.000000    1.000000  
max      2.420000   81.000000    1.000000

In [110]:
type(df)

pandas.core.frame.DataFrame

In [112]:
type(df['Populasi'])

pandas.core.series.Series

In [104]:
obj_series['Bandung':'Jawa']

Bandung    10
Jawa        8
dtype: int64

In [94]:
obj_series.index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [95]:
obj_series.values

array([1, 2, 3, 4], dtype=int64)

In [96]:
obj_series

A    1
B    2
C    3
D    4
dtype: int64

In [1]:
!dir

 Volume in drive C has no label.
 Volume Serial Number is 4806-0654

 Directory of C:\Users\LENOVO\Python Data Science\sanbercode 092020

10/05/2020  06:45 PM    <DIR>          .
10/05/2020  06:45 PM    <DIR>          ..
10/05/2020  06:26 PM    <DIR>          .ipynb_checkpoints
09/30/2020  09:04 PM            11,281 Logic Control flow and Loop.ipynb
10/05/2020  06:44 PM             1,305 Numpy Pandas.ipynb
05/08/2020  09:32 PM            24,045 pima indians dataset.csv
10/01/2020  09:22 PM            23,086 Python List dan Dictionary.ipynb
10/03/2020  01:54 PM           117,956 Statistik.ipynb
09/28/2020  09:16 PM             3,983 Tugas Hari 1 (1).ipynb
09/29/2020  09:31 PM             5,466 Tugas Hari 2.ipynb
10/01/2020  09:54 PM            11,269 Tugas Hari 3.ipynb
10/01/2020  07:39 PM            13,653 Tugas Hari 4.ipynb
09/29/2020  08:38 PM            19,533 Tugas Hari 5.ipynb
09/29/2020  09:17 PM             3,229 Untitled.ipynb
              11 File(s)        234,806 bytes
     

In [4]:
[1, 'str', 3, True]

[1, 'str', 3, True]

In [5]:
import numpy as np
np.array([1, 2, 3, 'str'])

array(['1', '2', '3', 'str'], dtype='<U11')

In [60]:
obj_numpy = np.array([
                [1, 2, 3, 1], [2, 3, 5, 3], [2, 3, 5, 3]
                ])


obj_list = [[1, 2], [2, 3]]

In [63]:
obj_numpy[1:, 2:]

array([[5, 3],
       [5, 3]])

In [74]:
obj_array_2 = np.arange(2, 10)

In [75]:
obj_array_2

array([2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
obj_array_2.shape

(8,)

In [80]:
obj_array_2.reshape(2, 2, 2)

array([[[2, 3],
        [4, 5]],

       [[6, 7],
        [8, 9]]])

In [81]:
obj_numpy_1 = np.array([1, 2, 3])
obj_numpy_2 = np.array([3, 4, 5])

In [84]:
np.concatenate([obj_numpy_1, obj_numpy_2])

array([1, 2, 3, 3, 4, 5])

In [85]:
obj_array_2 = np.arange(2, 10)

In [86]:
obj_array_2

array([2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
obj_array_2[::2]

array([2, 4, 6, 8])

In [46]:
obj_numpy.ndim

3

In [52]:
obj_numpy.shape

(2, 2, 4)

In [51]:
# satuannya bytes
obj_numpy.itemsize

4

In [53]:
obj_numpy.nbytes

64

- Numpy lebih cepat di bandingkan list
- isi data nya cuma satu tipe data
- Mengenal yang namanya multi-dimension
- Memiliki banyak method untuk melakukan manipulasi data

In [ ]:
np.mean()